# Generated by Django 5.0.1 on 2024-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_desc', models.CharField(max_length=100)),
                ('pro_img', models.ImageField(upload_to='Product Img')),
            ],
        ),
    ]
